import type { Metadata } from "next";
import "./globals.css";
import App from "./App";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout component for the application.
 * It wraps the entire application with the Next.js `<html>` element,
 * and includes the necessary meta tags, stylesheets, and script tags.
 * It also sets up the Next.js `<body>` element with the necessary classes.
 * @param children The children of the component, which is the entire application.
 * @returns The root layout component.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <head>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="theme-color" content="#000000" />
        <base href="/" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel="shortcut icon" href="/favicon.ico" />
        <noscript id="emotion-insertion-point" />
      </head>
      <body id="root" className="min-h-full flex flex-col">
        <App>{children}</App>
      </body>
    </html>
  );
}
